# Generated by Django 2.2.5 on 2021-05-04 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_auto_20210504_1619'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
